<a href="https://colab.research.google.com/github/hamzi27/adv-ml-assignment1/blob/master/ass1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Amrani Hamza - 807386

## Load data

In [8]:
import pandas as pd
import numpy as np


def load_data(path, train=True):
    """Load data from a CSV File
    
    Parameters
    ----------
    path: str
        The path to the CSV file
        
    train: bool (default True)
        Decide whether or not data are *training data*.
        If True, some random shuffling is applied.
        
    Return
    ------
    X: numpy.ndarray 
        The data as a multi dimensional array of floats
    ids: numpy.ndarray
        A vector of ids for each sample
    """
    text = pd.read_csv(path, encoding = "ISO-8859-2")
    df = pd.read_csv(path)
    X = df.values.copy()
    if train:
        np.random.shuffle(X)  
        X, labels = X[:, 1:-1].astype(np.float32), X[:, -1]
        return X, labels
    else:
        X, ids = X[:, 1:].astype(np.float32), X[:, 0].astype(str)
        return X, ids

url_train = 'https://raw.githubusercontent.com/hamzi27/adv-ml-assignment1/master/train.csv'
url_test = 'https://raw.githubusercontent.com/hamzi27/adv-ml-assignment1/master/test.csv'

X_train, Y_train = load_data(url_train, train=True)
X_test, Y_test = load_data(url_test, train=False)

print("Training set data")
print(X_train)

print("Training set labels")
print(Y_train)

Training set data
[[2.0000e+00 1.0000e+00 1.0000e+00 ... 1.0000e+03 5.2000e+02 3.2500e+02]
 [2.0000e+00 2.0000e+00 1.0000e+00 ... 1.6000e+03 1.6000e+03 2.0000e+03]
 [1.0000e+00 1.0000e+00 1.0000e+00 ... 1.1720e+03 2.2460e+03 1.1720e+03]
 ...
 [2.0000e+00 2.0000e+00 1.0000e+00 ... 7.0100e+03 7.0130e+03 7.0150e+03]
 [1.0000e+00 2.0000e+00 2.0000e+00 ... 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e+00 1.0000e+00 2.0000e+00 ... 4.0700e+03 2.5900e+02 1.1675e+04]]
Training set labels
[0. 0. 0. ... 0. 0. 0.]


# Preprocessing

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

def preprocess_labels(labels, encoder=None, categorical=True):
    """Encode labels with values among 0 and `n-classes-1`"""
    if not encoder:
        encoder = LabelEncoder()
        encoder.fit(labels)
    y = encoder.transform(labels).astype(np.int32)
    if categorical:
        y = np_utils.to_categorical(y)
    return y, encoder
  
  
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


Y_train, encoder = preprocess_labels(Y_train)


nb_classes = Y_train.shape[1]
print(nb_classes, 'classes')

dims = X_train.shape[1]
print(dims, 'dims')



2 classes
22 dims


# Using Keras

In [24]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers.core import Activation
import matplotlib.pyplot as plt


model = Sequential()

model.add(Dense(100, input_shape=(dims,)))
model.add(Dense(80))
model.add(Dense(50))

model.add(Dense(nb_classes))
model.add(Activation('softmax'))
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


model.fit(X_train, Y_train, validation_split=0.2, epochs=20, batch_size=32, verbose=True)
model.evaluate(X_test, Y_test)


plt.plot(hist.history['loss'])
plt.plot(hist.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='upper right')
plt.show()




Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 100)               2300      
_________________________________________________________________
dense_15 (Dense)             (None, 80)                8080      
_________________________________________________________________
dense_16 (Dense)             (None, 50)                4050      
_________________________________________________________________
dense_17 (Dense)             (None, 2)                 102       
_________________________________________________________________
activation_6 (Activation)    (None, 2)                 0         
Total params: 14,532
Trainable params: 14,532
Non-trainable params: 0
_________________________________________________________________
Train on 21600 samples, validate on 5400 samples
Epoch 1/10
21600/21600 [==============================] - 1s 61us/s

ValueError: ignored